/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TriageVoiceRouteImport } from './routes/triage-voice'
import { Route as PrescriptionRxRouteImport } from './routes/prescription-rx'
import { Route as NutritionScanRouteImport } from './routes/nutrition-scan'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const TriageVoiceRoute = TriageVoiceRouteImport.update({
  id: '/triage-voice',
  path: '/triage-voice',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionRxRoute = PrescriptionRxRouteImport.update({
  id: '/prescription-rx',
  path: '/prescription-rx',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionScanRoute = NutritionScanRouteImport.update({
  id: '/nutrition-scan',
  path: '/nutrition-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/labs': typeof LabsRoute
  '/nutrition-scan': typeof NutritionScanRoute
  '/prescription-rx': typeof PrescriptionRxRoute
  '/triage-voice': typeof TriageVoiceRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/labs': typeof LabsRoute
  '/nutrition-scan': typeof NutritionScanRoute
  '/prescription-rx': typeof PrescriptionRxRoute
  '/triage-voice': typeof TriageVoiceRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/labs': typeof LabsRoute
  '/nutrition-scan': typeof NutritionScanRoute
  '/prescription-rx': typeof PrescriptionRxRoute
  '/triage-voice': typeof TriageVoiceRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/labs'
    | '/nutrition-scan'
    | '/prescription-rx'
    | '/triage-voice'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/labs'
    | '/nutrition-scan'
    | '/prescription-rx'
    | '/triage-voice'
    | '/api/chat'
  id:
    | '__root__'
    | '/labs'
    | '/nutrition-scan'
    | '/prescription-rx'
    | '/triage-voice'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LabsRoute: typeof LabsRoute
  NutritionScanRoute: typeof NutritionScanRoute
  PrescriptionRxRoute: typeof PrescriptionRxRoute
  TriageVoiceRoute: typeof TriageVoiceRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/triage-voice': {
      id: '/triage-voice'
      path: '/triage-voice'
      fullPath: '/triage-voice'
      preLoaderRoute: typeof TriageVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescription-rx': {
      id: '/prescription-rx'
      path: '/prescription-rx'
      fullPath: '/prescription-rx'
      preLoaderRoute: typeof PrescriptionRxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition-scan': {
      id: '/nutrition-scan'
      path: '/nutrition-scan'
      fullPath: '/nutrition-scan'
      preLoaderRoute: typeof NutritionScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LabsRoute: LabsRoute,
  NutritionScanRoute: NutritionScanRoute,
  PrescriptionRxRoute: PrescriptionRxRoute,
  TriageVoiceRoute: TriageVoiceRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
